export default {
  edit: [],
  users: [
    {
      id: "1",
      firstName: "Andres Felipe",
      lastName: "Garcia Castro",
      identification: 1144485404,
      role: "Administrador",
      state: "Activo",
      phone: "3165303978",
      email: "afgarcia@refinal.com",
    },
    {
      id: "2",
      firstName: "Elizabeth",
      lastName: "Arboleda",
      identification: 665789080,
      role: "Administrador",
      state: "Inactivo",
      phone: "3165303978",
      email: "earboleda@refinal.com",
    },
    {
      id: "3",
      firstName: "Jader",
      lastName: "Penagos",
      identification: 665789043,
      role: "Conductor",
      state: "Activo",
      phone: "3175303978",
      email: "jpenagos@refinal.com",
    },
    {
      id: "4",
      firstName: "Diana",
      lastName: "Villa",
      identification: 1122567890,
      role: "Recolector",
      state: "Activo",
      phone: "3005303976",
      email: "dvilla@refinal.com",
    },
  ],
};
