export default {
  edit: [],
  users: [
    {
      id: "1",
      firstName: "Andres Felipe",
      lastName: "Garcia Castro",
      identification: 1144485404,
      role: "Administrador",
      state: "Activo",
      phone: "3165303978",
      email: "afgarcia@refinal.com",
    },
    {
      id: "2",
      firstName: "Elizabeth",
      lastName: "Arboleda",
      identification: 665789080,
      role: "Administrador",
      state: "Inactivo",
      phone: "3165303978",
      email: "earboleda@refinal.com",
    },
    {
      id: "3",
      firstName: "Jader",
      lastName: "Penagos",
      identification: 665789043,
      role: "Conductor",
      state: "Activo",
      phone: "3175303978",
      email: "jpenagos@refinal.com",
    },
    {
      id: "4",
      firstName: "Diana",
      lastName: "Villa",
      identification: 1122567890,
      role: "Recolector",
      state: "Activo",
      phone: "3005303976",
      email: "dvilla@refinal.com",
    },
    {
      id: "5",
      firstName: "Luis Andrés",
      lastName: "Murillo",
      identification: 1144198789,
      role: "Administrador",
      state: "Activo",
      phone: "3115134078",
      email: "lamurillo@refinal.com",
    },
    {
      id: "6",
      firstName: "Luis Andrés",
      lastName: "Murillo",
      identification: 1144198789,
      role: "Administrador",
      state: "Activo",
      phone: "3115134078",
      email: "lamurillo@refinal.com",
    },
    {
      id: "7",
      firstName: "Jairo",
      lastName: "Gutierrez",
      identification: 44789056,
      role: "Coordinador",
      state: "Activo",
      phone: "3125333977",
      email: "jgutierrez@refinal.com",
    },
    {
      id: "8",
      firstName: "Alexandra",
      lastName: "Culcha",
      identification: 1144198786,
      role: "Digitador CG-UNO",
      state: "Inactivo",
      phone: "3145439560",
      email: "aculcha@refinal.com",
    },
    {
      id: "9",
      firstName: "Valentina",
      lastName: "Zapata",
      identification: 72567788,
      role: "Recolector",
      state: "Activo",
      phone: "3157893970",
      email: "vzapata@refinal.com",
    },
  ],
};
